language: php

php:
  - 7.0.7
before_script:
  - php composer.phar install
  - cp .env.example .env
  - mysql -e "CREATE DATABASE sm_test" -uroot
  - php artisan migrate
  - php artisan key:generate

script:
  - ./vendor/bin/phpunit tests
